# Usage: docker compose --env-file env.sh up -d

services:
  traefik:
    container_name: ${CONTAINER_NAME}
    image: traefik:${VERSION}
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ${CERTS_PATH}:/certs:ro
      - ${DOCKER_SOCKET}:/var/run/docker.sock:ro
      - ${CONFIG_DIR}:/etc/traefik:ro
    labels:
      - "traefik.enable=true"
    networks:
      - traefik-public

networks:
  traefik-public:
    name: ${NETWORK}
    external: true
