log:
  level: DEBUG

api:
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  postgres:
    address: ":5432"
  mysql:
    address: ":3306"
  redis:
    address: ":6379"
  rabbitmq:
    address: ":5672"

providers:
  docker:
    exposedByDefault: false
